from .industry import *

CORES = {
    Industry.TECH: [
        "Systems",
        "Digital",
        "Logic",
        "Software",
        "Networks",
        "Cloud",
        "Data",
        "Computing",
    ],

    Industry.FIN: [
        "Capital",
        "Finance",
        "Invest",
        "Asset",
        "Equity",
        "Trust",
        "Wealth",
        "Securities",
    ],

    Industry.HEALTH: [
        "Medical",
        "Bio",
        "Pharma",
        "Health",
        "Care",
        "Diagnostics",
        "Therapeutics",
        "Life",
    ],

    Industry.ENERGY: [
        "Energy",
        "Power",
        "Resources",
        "Renewable",
        "Electric",
        "Grid",
        "Fuel",
        "Dynamics",
    ],

    Industry.MFG: [
        "Manufacturing",
        "Industries",
        "Engineering",
        "Machines",
        "Systems",
        "Precision",
        "Materials",
        "Works",
    ],

    Industry.RETAIL: [
        "Retail",
        "Market",
        "Commerce",
        "Stores",
        "Brands",
        "Trade",
        "Supply",
        "Goods",
    ],

    Industry.CONS: [
        "Consumer",
        "Products",
        "Goods",
        "Lifestyle",
        "Brands",
        "Home",
        "Living",
        "Solutions",
    ],

    Industry.TELECOM: [
        "Communications",
        "Networks",
        "Wireless",
        "Connect",
        "Signal",
        "Mobile",
        "Telecom",
        "Systems",
    ],

    Industry.TRANS: [
        "Transport",
        "Logistics",
        "Mobility",
        "Shipping",
        "Transit",
        "Cargo",
        "Freight",
        "Solutions",
    ],

    Industry.REALEST: [
        "Realty",
        "Properties",
        "Estates",
        "Development",
        "Residences",
        "Holdings",
        "Assets",
    ],

    Industry.CONSTR: [
        "Construction",
        "Builders",
        "Engineering",
        "Infrastructure",
        "Structures",
        "Development",
        "Projects",
        "Works",
    ],

    Industry.MINING: [
        "Mining",
        "Minerals",
        "Metals",
        "Resources",
        "Materials",
        "Extraction",
        "Earth",
        "Ore",
    ],

    Industry.AGRI: [
        "Agriculture",
        "Farms",
        "Agro",
        "Harvest",
        "Growers",
        "Fields",
        "Resources",
    ],

    Industry.FOOD: [
        "Foods",
        "Beverage",
        "Nutrition",
        "Cuisine",
        "Kitchen",
        "Brands",
        "Taste",
        "Consumer",
    ],

    Industry.MEDIA: [
        "Media",
        "Entertainment",
        "Studios",
        "Digital",
        "Content",
        "Vision",
        "Creative",
        "Network",
    ],

    Industry.UTIL: [
        "Utilities",
        "Power",
        "Water",
        "Energy",
        "Services",
        "Networks",
        "Resources",
        "Infrastructure",
    ],

    Industry.AERO: [
        "Aerospace",
        "Defense",
        "Systems",
        "Aviation",
        "Dynamics",
        "Technologies",
        "Engineering",
        "Space",
    ],

    Industry.AUTO: [
        "Motors",
        "Automotive",
        "Mobility",
        "Vehicles",
        "Drive",
        "Machines",
        "Engineering",
        "Dynamics",
    ],

    Industry.CHEM: [
        "Chemicals",
        "Materials",
        "Solutions",
        "Elements",
        "Science",
        "Polymers",
        "Industries",
        "Research",
    ],

    Industry.TOUR: [
        "Hotels",
        "Resorts",
        "Travel",
        "Hospitality",
        "Tourism",
        "Leisure",
        "Destinations",
        "Experiences",
    ],
}